[package]
name = "tantivy-bench"
version = "0.1.0"
authors = ["jwolfe"]

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"

[dependencies.tantivy]
git = "https://github.com/tantivy-search/tantivy.git"
rev = "20bede946204bf6f5ea1cac7e3b70cf731e34413"
