[package]
name = "tantivy-bench"
version = "0.1.0"
authors = ["jwolfe"]

[dependencies]
tantivy = "0.4.4"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"

[[bin]]
name = "build_index"
path = "src/build_index.rs"