[package]
name = "tantivy-bench"
version = "0.1.0"
authors = ["Jason Wolfe"]

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"

[dependencies.tantivy]
git = "https://github.com/tantivy-search/tantivy.git"
rev = "1fc7afa90a69d47d836ea22bae2da785fb75dad7"