[package]
name = "tantivy-bench"
version = "0.1.0"
authors = ["jwolfe"]

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"

[dependencies.tantivy]
git = "https://github.com/tantivy-search/tantivy.git"
rev = "42fd3fe5c7cab9c342baa6c6098b20e2a6f82183"
